domains:
  - domain: dev.api.tutorpal.io
    type: PRIMARY
    zone: tutorpal.io
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: backend
      cors:
        allow_credentials: true
        allow_headers:
          - Content-Type
        allow_methods:
          - GET
          - HEAD
          - POST
          - OPTIONS
          - PUT
          - PATCH
          - DELETE
        allow_origins:
          - exact: https://dev.tutorpal.io
      match:
        path:
          prefix: /
name: tutor-pal-backend-dev
region: sgp
services:
  - envs:
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "3000"
      - key: CORS_ORIGIN
        scope: RUN_AND_BUILD_TIME
        value: https://dev.tutorpal.io
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:F/4n8QMTkQBG1khhBdlCGRnZpTU6j3K3:h/V/tpeXD6Y8vUolt4FI/pUVdMCavolK8VXirLnC4UcWqjhUmanUhjhA+Bdy49oxQfcLkCRf4kXQcJ9Kn9Gx8hqk/kfXhcEV+3FiVPgb8tUG8uyA/3eB5px3jPXijwz+VTuBIxWQc+Qkm40HPZS5KDPzjnxYz2SX7U6MQVA8guq+bBkd55UhNagmbXNf54uUwq0qR4wSKw==]
      - key: BETTER_AUTH_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:vW4dmFfO0Od8KCDytA5F3+fSaFLYDFMO:t+2v8BLCika22fJ7gK8IMELdCl8NbuX84bE+5Lb5vIDzz9zwO/8W4nUQRGlwWK9GyZOAnERIJ39eTAgMupAmx/3BwaLm2iefED1a+VRTDCJknONOJjm2pBfJesRs52tdRCrZZKblASlgEkJCojyjT+KEgWicg1YpBeGTQ8JfyVHBocW30g4WAVoz2ZshRhk1]
      - key: BETTER_AUTH_URL
        scope: RUN_AND_BUILD_TIME
        value: https://dev.api.tutorpal.io
      - key: LINE_LOGIN_CHANNEL_ID
        scope: RUN_AND_BUILD_TIME
        value: "2009982245"
      - key: LINE_LOGIN_CHANNEL_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:nKPjGzLmbllwOQlMNisAFyYl1dTe/u4p:x9iwAPnImMQLaA3el5KZQw==]
      - key: LINE_LINK_REDIRECT_URL
        scope: RUN_AND_BUILD_TIME
        value: https://dev.api.tutorpal.io/v1/line/callback
      - key: FRONTEND_URL
        scope: RUN_AND_BUILD_TIME
        value: https://dev.tutorpal.io
      - key: LINE_MESSAGING_CHANNEL_ACCESS_TOKEN
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:sBwRDGdT5KbSVFhyIG3XYxV4hiawCZoM:0e/x0KpaVI3v7f83SL5VV57wAn4OHLhAtULnFtuqxiEMniUdW1zcuS2uLoypaKdEXXRfEIyaw4kdH98OcCrUnR41MFdvXjCmz6YzHWuiPKrYu8a1wO5MTXUBctY0SkGlTU+HLYryYYedc4/O1vXJcQy+xEu6IGLnzdldGL1aJkZwtz8wljqqRL4UWPk0VolV2TZLAeqBkpjAy3ZEjvkH0LChvXVC9ofepkz0eE42Hfit9+4vzafvLntx+p0=]
      - key: RESEND_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:F2UAOJwPQtSqeSa6ol1wYyeA0d7Oo4LF:GSGKQwH9O5haXnTiCrlpNjNqc0gbYtlFi9QJoaJrLtQQT2GLxc1TwDB8wmDRU/B3rbu8eA==]
      - key: RESEND_FROM_EMAIL
        scope: RUN_AND_BUILD_TIME
        value: TutorPal <no-reply@tutorpal.io>
      - key: EMAIL_VERIFICATION_CALLBACK_URL
        scope: RUN_AND_BUILD_TIME
        value: https://dev.tutorpal.io/verify-email
    health_check:
      failure_threshold: 3
      http_path: /v1/health
      initial_delay_seconds: 10
      period_seconds: 10
      port: 3000
      success_threshold: 1
      timeout_seconds: 5
    http_port: 3000
    image:
      registry: tutor-pal
      registry_type: DOCR
      repository: backend
      tag: dev
    instance_count: 1
    instance_size_slug: basic-xxs
    name: backend
