export const APP_ROUTES = {
	LOGIN: "/login",
	SIGNUP: "/signup",
	FORGOT_PASSWORD: "/forgot-password",
	RESET_PASSWORD: "/reset-password",
	VERIFY_EMAIL: "/verify-email",
	HOME: "/",
	STUDENTS: "/students",
	STUDENT_DETAIL: "/students/$studentId",
	CLASSES: "/classes",
	CLASS_DETAIL: "/classes/$classId",
	SCHEDULES: "/schedules",
	SETTINGS: "/settings",
	LINE_SETTINGS: "/settings/line",
};
