/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LineLinkRouteImport } from './routes/line-link'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutStudentsRouteImport } from './routes/_layout/students'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSchedulesRouteImport } from './routes/_layout/schedules'
import { Route as LayoutCoursesRouteImport } from './routes/_layout/courses'
import { Route as LayoutClassesRouteImport } from './routes/_layout/classes'
import { Route as LayoutStudentsIndexRouteImport } from './routes/_layout/students/index'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutCoursesIndexRouteImport } from './routes/_layout/courses/index'
import { Route as LayoutClassesIndexRouteImport } from './routes/_layout/classes/index'
import { Route as LayoutStudentsStudentIdRouteImport } from './routes/_layout/students/$studentId'
import { Route as LayoutSettingsLineRouteImport } from './routes/_layout/settings/line'
import { Route as LayoutCoursesCourseIdRouteImport } from './routes/_layout/courses/$courseId'
import { Route as LayoutClassesClassIdRouteImport } from './routes/_layout/classes/$classId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LineLinkRoute = LineLinkRouteImport.update({
  id: '/line-link',
  path: '/line-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStudentsRoute = LayoutStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSchedulesRoute = LayoutSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCoursesRoute = LayoutCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClassesRoute = LayoutClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStudentsIndexRoute = LayoutStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutStudentsRoute,
} as any).lazy(() =>
  import('./routes/_layout/students/index.lazy').then((d) => d.Route),
)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutCoursesIndexRoute = LayoutCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCoursesRoute,
} as any).lazy(() =>
  import('./routes/_layout/courses/index.lazy').then((d) => d.Route),
)
const LayoutClassesIndexRoute = LayoutClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutClassesRoute,
} as any).lazy(() =>
  import('./routes/_layout/classes/index.lazy').then((d) => d.Route),
)
const LayoutStudentsStudentIdRoute = LayoutStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => LayoutStudentsRoute,
} as any)
const LayoutSettingsLineRoute = LayoutSettingsLineRouteImport.update({
  id: '/line',
  path: '/line',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutCoursesCourseIdRoute = LayoutCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => LayoutCoursesRoute,
} as any)
const LayoutClassesClassIdRoute = LayoutClassesClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => LayoutClassesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/line-link': typeof LineLinkRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/classes': typeof LayoutClassesRouteWithChildren
  '/courses': typeof LayoutCoursesRouteWithChildren
  '/schedules': typeof LayoutSchedulesRoute
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/students': typeof LayoutStudentsRouteWithChildren
  '/classes/$classId': typeof LayoutClassesClassIdRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdRoute
  '/settings/line': typeof LayoutSettingsLineRoute
  '/students/$studentId': typeof LayoutStudentsStudentIdRoute
  '/classes/': typeof LayoutClassesIndexRoute
  '/courses/': typeof LayoutCoursesIndexRoute
  '/settings/': typeof LayoutSettingsIndexRoute
  '/students/': typeof LayoutStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/line-link': typeof LineLinkRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/schedules': typeof LayoutSchedulesRoute
  '/': typeof LayoutIndexRoute
  '/classes/$classId': typeof LayoutClassesClassIdRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdRoute
  '/settings/line': typeof LayoutSettingsLineRoute
  '/students/$studentId': typeof LayoutStudentsStudentIdRoute
  '/classes': typeof LayoutClassesIndexRoute
  '/courses': typeof LayoutCoursesIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/students': typeof LayoutStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/line-link': typeof LineLinkRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_layout/classes': typeof LayoutClassesRouteWithChildren
  '/_layout/courses': typeof LayoutCoursesRouteWithChildren
  '/_layout/schedules': typeof LayoutSchedulesRoute
  '/_layout/settings': typeof LayoutSettingsRouteWithChildren
  '/_layout/students': typeof LayoutStudentsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/classes/$classId': typeof LayoutClassesClassIdRoute
  '/_layout/courses/$courseId': typeof LayoutCoursesCourseIdRoute
  '/_layout/settings/line': typeof LayoutSettingsLineRoute
  '/_layout/students/$studentId': typeof LayoutStudentsStudentIdRoute
  '/_layout/classes/': typeof LayoutClassesIndexRoute
  '/_layout/courses/': typeof LayoutCoursesIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/students/': typeof LayoutStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/line-link'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/classes'
    | '/courses'
    | '/schedules'
    | '/settings'
    | '/students'
    | '/classes/$classId'
    | '/courses/$courseId'
    | '/settings/line'
    | '/students/$studentId'
    | '/classes/'
    | '/courses/'
    | '/settings/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/line-link'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/schedules'
    | '/'
    | '/classes/$classId'
    | '/courses/$courseId'
    | '/settings/line'
    | '/students/$studentId'
    | '/classes'
    | '/courses'
    | '/settings'
    | '/students'
  id:
    | '__root__'
    | '/_layout'
    | '/forgot-password'
    | '/line-link'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_layout/classes'
    | '/_layout/courses'
    | '/_layout/schedules'
    | '/_layout/settings'
    | '/_layout/students'
    | '/_layout/'
    | '/_layout/classes/$classId'
    | '/_layout/courses/$courseId'
    | '/_layout/settings/line'
    | '/_layout/students/$studentId'
    | '/_layout/classes/'
    | '/_layout/courses/'
    | '/_layout/settings/'
    | '/_layout/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LineLinkRoute: typeof LineLinkRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-link': {
      id: '/line-link'
      path: '/line-link'
      fullPath: '/line-link'
      preLoaderRoute: typeof LineLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/students': {
      id: '/_layout/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof LayoutStudentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/schedules': {
      id: '/_layout/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof LayoutSchedulesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/courses': {
      id: '/_layout/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof LayoutCoursesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/classes': {
      id: '/_layout/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof LayoutClassesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/students/': {
      id: '/_layout/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof LayoutStudentsIndexRouteImport
      parentRoute: typeof LayoutStudentsRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/courses/': {
      id: '/_layout/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof LayoutCoursesIndexRouteImport
      parentRoute: typeof LayoutCoursesRoute
    }
    '/_layout/classes/': {
      id: '/_layout/classes/'
      path: '/'
      fullPath: '/classes/'
      preLoaderRoute: typeof LayoutClassesIndexRouteImport
      parentRoute: typeof LayoutClassesRoute
    }
    '/_layout/students/$studentId': {
      id: '/_layout/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof LayoutStudentsStudentIdRouteImport
      parentRoute: typeof LayoutStudentsRoute
    }
    '/_layout/settings/line': {
      id: '/_layout/settings/line'
      path: '/line'
      fullPath: '/settings/line'
      preLoaderRoute: typeof LayoutSettingsLineRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/courses/$courseId': {
      id: '/_layout/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof LayoutCoursesCourseIdRouteImport
      parentRoute: typeof LayoutCoursesRoute
    }
    '/_layout/classes/$classId': {
      id: '/_layout/classes/$classId'
      path: '/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof LayoutClassesClassIdRouteImport
      parentRoute: typeof LayoutClassesRoute
    }
  }
}

interface LayoutClassesRouteChildren {
  LayoutClassesClassIdRoute: typeof LayoutClassesClassIdRoute
  LayoutClassesIndexRoute: typeof LayoutClassesIndexRoute
}

const LayoutClassesRouteChildren: LayoutClassesRouteChildren = {
  LayoutClassesClassIdRoute: LayoutClassesClassIdRoute,
  LayoutClassesIndexRoute: LayoutClassesIndexRoute,
}

const LayoutClassesRouteWithChildren = LayoutClassesRoute._addFileChildren(
  LayoutClassesRouteChildren,
)

interface LayoutCoursesRouteChildren {
  LayoutCoursesCourseIdRoute: typeof LayoutCoursesCourseIdRoute
  LayoutCoursesIndexRoute: typeof LayoutCoursesIndexRoute
}

const LayoutCoursesRouteChildren: LayoutCoursesRouteChildren = {
  LayoutCoursesCourseIdRoute: LayoutCoursesCourseIdRoute,
  LayoutCoursesIndexRoute: LayoutCoursesIndexRoute,
}

const LayoutCoursesRouteWithChildren = LayoutCoursesRoute._addFileChildren(
  LayoutCoursesRouteChildren,
)

interface LayoutSettingsRouteChildren {
  LayoutSettingsLineRoute: typeof LayoutSettingsLineRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
}

const LayoutSettingsRouteChildren: LayoutSettingsRouteChildren = {
  LayoutSettingsLineRoute: LayoutSettingsLineRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
}

const LayoutSettingsRouteWithChildren = LayoutSettingsRoute._addFileChildren(
  LayoutSettingsRouteChildren,
)

interface LayoutStudentsRouteChildren {
  LayoutStudentsStudentIdRoute: typeof LayoutStudentsStudentIdRoute
  LayoutStudentsIndexRoute: typeof LayoutStudentsIndexRoute
}

const LayoutStudentsRouteChildren: LayoutStudentsRouteChildren = {
  LayoutStudentsStudentIdRoute: LayoutStudentsStudentIdRoute,
  LayoutStudentsIndexRoute: LayoutStudentsIndexRoute,
}

const LayoutStudentsRouteWithChildren = LayoutStudentsRoute._addFileChildren(
  LayoutStudentsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutClassesRoute: typeof LayoutClassesRouteWithChildren
  LayoutCoursesRoute: typeof LayoutCoursesRouteWithChildren
  LayoutSchedulesRoute: typeof LayoutSchedulesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRouteWithChildren
  LayoutStudentsRoute: typeof LayoutStudentsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutClassesRoute: LayoutClassesRouteWithChildren,
  LayoutCoursesRoute: LayoutCoursesRouteWithChildren,
  LayoutSchedulesRoute: LayoutSchedulesRoute,
  LayoutSettingsRoute: LayoutSettingsRouteWithChildren,
  LayoutStudentsRoute: LayoutStudentsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LineLinkRoute: LineLinkRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
