/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LineLinkRouteImport } from './routes/line-link'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutStudentsRouteImport } from './routes/_layout/students'
import { Route as LayoutSchedulesRouteImport } from './routes/_layout/schedules'
import { Route as LayoutClassesRouteImport } from './routes/_layout/classes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LineLinkRoute = LineLinkRouteImport.update({
  id: '/line-link',
  path: '/line-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStudentsRoute = LayoutStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSchedulesRoute = LayoutSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClassesRoute = LayoutClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/line-link': typeof LineLinkRoute
  '/login': typeof LoginRoute
  '/classes': typeof LayoutClassesRoute
  '/schedules': typeof LayoutSchedulesRoute
  '/students': typeof LayoutStudentsRoute
}
export interface FileRoutesByTo {
  '/line-link': typeof LineLinkRoute
  '/login': typeof LoginRoute
  '/classes': typeof LayoutClassesRoute
  '/schedules': typeof LayoutSchedulesRoute
  '/students': typeof LayoutStudentsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/line-link': typeof LineLinkRoute
  '/login': typeof LoginRoute
  '/_layout/classes': typeof LayoutClassesRoute
  '/_layout/schedules': typeof LayoutSchedulesRoute
  '/_layout/students': typeof LayoutStudentsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/line-link'
    | '/login'
    | '/classes'
    | '/schedules'
    | '/students'
  fileRoutesByTo: FileRoutesByTo
  to: '/line-link' | '/login' | '/classes' | '/schedules' | '/students' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/line-link'
    | '/login'
    | '/_layout/classes'
    | '/_layout/schedules'
    | '/_layout/students'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LineLinkRoute: typeof LineLinkRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-link': {
      id: '/line-link'
      path: '/line-link'
      fullPath: '/line-link'
      preLoaderRoute: typeof LineLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/students': {
      id: '/_layout/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof LayoutStudentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/schedules': {
      id: '/_layout/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof LayoutSchedulesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/classes': {
      id: '/_layout/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof LayoutClassesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutClassesRoute: typeof LayoutClassesRoute
  LayoutSchedulesRoute: typeof LayoutSchedulesRoute
  LayoutStudentsRoute: typeof LayoutStudentsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutClassesRoute: LayoutClassesRoute,
  LayoutSchedulesRoute: LayoutSchedulesRoute,
  LayoutStudentsRoute: LayoutStudentsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LineLinkRoute: LineLinkRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
